sudo: required

services:
  - docker

before_install:
  - docker build -t react-docker -f Dockerfile.dev .

script:
  - docker run react-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-216272097231"
  bucket_path: "docker"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
  on:
    branch: master
