FROM node:alpine
WORKDIR '/app'
COPY package.json .

RUN npm install
RUN npm cache clean --force
RUN echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p

#COPY . .

CMD ["npm", "run", "start"]