FROM node:alpine
WORKDIR '/app'
COPY package.json .
RUN echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
RUN npm install

#COPY . .

CMD ["npm", "run", "start"]